# Generated by Django 5.2.4 on 2026-07-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Mobiles', 'Mobiles'), ('Laptops', 'Laptops'), ('Accessories', 'Accessories')], default='Mobiles', max_length=50),
        ),
    ]
